/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementRouteImport } from './routes/announcement'
import { Route as DressCodeRouteImport } from './routes/dress-code'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as PlanRouteImport } from './routes/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementRoute = AnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const DressCodeRoute = DressCodeRouteImport.update({
  id: '/dress-code',
  path: '/dress-code',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRoute
  '/dress-code': typeof DressCodeRoute
  '/invitation': typeof InvitationRoute
  '/letter': typeof LetterRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRoute
  '/dress-code': typeof DressCodeRoute
  '/invitation': typeof InvitationRoute
  '/letter': typeof LetterRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRoute
  '/dress-code': typeof DressCodeRoute
  '/invitation': typeof InvitationRoute
  '/letter': typeof LetterRoute
  '/plan': typeof PlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/announcement' | '/dress-code' | '/invitation' | '/letter' | '/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/announcement' | '/dress-code' | '/invitation' | '/letter' | '/plan'
  id:
    | '__root__'
    | '/'
    | '/announcement'
    | '/dress-code'
    | '/invitation'
    | '/letter'
    | '/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementRoute: typeof AnnouncementRoute
  DressCodeRoute: typeof DressCodeRoute
  InvitationRoute: typeof InvitationRoute
  LetterRoute: typeof LetterRoute
  PlanRoute: typeof PlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement': {
      id: '/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dress-code': {
      id: '/dress-code'
      path: '/dress-code'
      fullPath: '/dress-code'
      preLoaderRoute: typeof DressCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementRoute: AnnouncementRoute,
  DressCodeRoute: DressCodeRoute,
  InvitationRoute: InvitationRoute,
  LetterRoute: LetterRoute,
  PlanRoute: PlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
